[package]
name = "luakit-common"
version = "0.1.0"
edition = "2024"

[profile.dev]
# debug = false

[lib]
name = "luakit_common"
path = "src/lib.rs"

[dependencies]
libc = "0.2.174"
mlua = { version = "0.10.5", features = [ "lua51" ] }
webkit2gtk-sys = { version = "2.0.1", features = [ "v2_16"] }
gio-sys = "0.18.1"
# glib = "0.18.1"
gobject-sys = "0.18.0"
glib-sys = { version = "0.18.1", features = ["v2_78"] }
gtk-sys = "0.18.1"
gdk-sys = "0.18.1"
javascriptcore-rs-sys = "1.1.1"
regex = "1.11.1"
